name: Terraform Apply

on:
  push:
    branches: 
      - main
    paths: 
      - 'terraform/**'

defaults:
  run:
    working-directory: ./terraform

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{secrets.TF_ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.TF_ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.TF_ARM_TENANT_ID}}
      TF_VAR_admin_username: ${{secrets.TF_VAR_ADMIN_USERNAME}}
      TF_VAR_admin_password: ${{secrets.TF_VAR_ADMIN_PASSWORD}}
      TF_VAR_admin_key_data: ${{secrets.TF_VAR_ADMIN_KEY_DATA}}
      TF_VAR_cyclecloud_username: ${{secrets.TF_VAR_CYCLECLOUD_USERNAME}}
      TF_VAR_cyclecloud_password: ${{secrets.TF_VAR_CYCLECLOUD_PASSWORD}}
      TF_VAR_cyclecloud_public_access_address_prefixes: ${{secrets.TF_VAR_CYCLECLOUD_PUBLIC_ACCESS_ADDRESS_PREFIXES}}
      TF_VAR_terraform_state_storage_account_name: ${{secrets.TF_VAR_TERRAFORM_STATE_STORAGE_ACCOUNT_NAME}}
    
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id:  plan
        run: terraform plan
        
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
